### ISSUE TITLE
some questions about the recommendations

### ISSUE THREAD

**Issue by CatherineSue** [rdevooght/sequence-based-recommendations#3]
Hi, I read your paper and code today, here are some questions I want to ask.

How do I print the recommendations for each user? For example, I add a new user and his interactions with some items, how do I get the recommendations for him by using the model I have trained?

**Comment by rdevooght** [comment]
Hi,

You made me realise that I didn't offer a way to get the recommendations for a user through command line.
I recognise that it would be indeed useful and I'll try to add that ASAP.

In the meantime however, you'll have to write some code to get the recommendations. I suggest that you read the file [test.py](https://github.com/rdevooght/sequence-based-recommendations/blob/master/test.py). You'll find in line 65 a call to the method `top_k_recommendations`, which is the method you'll have to use to get the recommendations.

**Comment by CatherineSue** [comment]
Got it, thanks!
