### ISSUE TITLE
next basket recommendation

### ISSUE THREAD

**Issue by richielo** [rdevooght/sequence-based-recommendations#6]
Hi,

Thank you for open sourcing the code and your work in the area. I am playing with an open source dataset and trying to do next basket recommendation. At the moment, I am trying to understand your paper and code thoroughly to see if it's applicable to my work. Do you think that's a good idea? or Do you have any suggestions on where to start? I am rather new to the area so bear with my ignorance. Thanks a lot for your help in advance!

**Comment by rdevooght** [comment]
Hi,

I am not fully versed in the specificities of next-basket recommendation, but I think that there is certainly a way to adapt the RNN approach to that problem.
In the following paper: http://bit.ly/umap_paper we compare the RNN with FPMC, which was originally designed for next-basket recommendation. In those experiments FPMC was simplified to deal with the standard item prediction problem, but you could take the other direction and adapt the RNN to the next-basket case.
Some have done that for feedforward neural network: http://ceur-ws.org/Vol-1441/recsys2015_poster15.pdf
It can be an inspiration for what you would have to do.

Best of luck,
Robin

**Comment by richielo** [comment]
Hi Robin,

Thank you very much for the reply. i will definitely look into it.

Richie
